### ISSUE TITLE
Some problem on Garuda and kde

### ISSUE THREAD

**Issue by Stibax** [lostallmymoney/Razer_Mouse_Linux#37]
Hi lostallmymoney,
i have changed distro from Manjaro cinnamon to Garuda KDE, and yesterday i install on the new system your Raazer_mouse.
The first problem i have faced is about when the install script check for dns connection. In my particular case it fails because in my firewall i have block port 53 and it redirects all dns traffic on dns over lts, so i change the script with port 853 and the script finish the installation. I know its only my particular case, for 99% of the system the port 53 it's open.
The real problems i facing are:
The wayland doens't compile. In manjaro no problem, but in my new install maybe i haven't all the requirement, i have to check better. For me it's not a problem because i have nvidia and with kde and wayland it doesn't go well.
The second problem is that when i finish the installation the programm works, but when i reboot no. the naga debug says:

mar 02 09:55:28 garuda systemd[1]: naga.service: Scheduled restart job, restart counter is at 1.
mar 02 09:55:28 garuda systemd[1]: Started Custom key bindings for the side panel of razer mouses..
mar 02 09:55:28 garuda nagaServerCatcher.sh[7282]: Starting X11
mar 02 09:55:28 garuda nagaServerCatcher.sh[7292]: Stopping possible naga daemon
mar 02 09:55:28 garuda nagaServerCatcher.sh[7309]: Authorization required, but no authorization protocol specified
mar 02 09:55:28 garuda nagaServerCatcher.sh[7309]: Unable to connect to X server
mar 02 09:55:28 garuda nagaServerCatcher.sh[7317]: Authorization required, but no authorization protocol specified
mar 02 09:55:28 garuda nagaServerCatcher.sh[7317]: Unable to connect to X server
mar 02 09:55:28 garuda nagaServerCatcher.sh[7292]: Reading from: /dev/input/by-id/usb-Razer_Razer_Naga_Pro_000000000000-if02-event-kbd
mar 02 09:55:28 garuda nagaServerCatcher.sh[7292]:  and /dev/input/by-id/usb-Razer_Razer_Naga_Pro_000000000000-event-mouse

If i remade the installation it starts to work.

The third problem is in kde XF86AudioRaiseVolume doesn't work, but Lower and Mute works. That's very stranghe, but i think is a kde problem.

Thanks again for your work and have a nice day.

**Comment by lostallmymoney** [comment]
Tell me if "naga start" works.
I got that error on wayland when it was trying ti start before any user logged in.
If it does work, try the command "who", count the number of rows, if you are above of 2 rows on a cleanly booted system maybe there's more sessions running so it would start too early.

Go inside of NagaServerCatcher and set the -lt condition to the number of outputs from who.

Tell me if it works.
Thanks
________________________________
From: Stibax ***@***.***>
Sent: Saturday, March 2, 2024 4:19:25 AM
To: lostallmymoney/Razer_Mouse_Linux ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [lostallmymoney/Razer_Mouse_Linux] Some problem on Garuda and kkde (Issue #37)


Hi lostallmymoney,
i have changed distro from Manjaro cinnamon to Garuda KDE, and yesterday i install on the new system your Raazer_mouse.
The first problem i have faced is about when the install script check for dns connection. In my particular case it fails because in my firewall i have block port 53 and it redirects all dns traffic on dns over lts, so i change the script with port 853 and the script finish the installation. I know its only my particular case, for 99% of the system the port 53 it's open.
The real problems i facing are:
The wayland doens't compile. In manjaro no problem, but in my new install maybe i haven't all the requirement, i have to check better. For me it's not a problem because i have nvidia and with kde and wayland it doesn't go well.
The second problem is that when i finish the installation the programm works, but when i reboot no. the naga debug says:

mar 02 09:55:28 garuda systemd[1]: naga.service: Scheduled restart job, restart counter is at 1.
mar 02 09:55:28 garuda systemd[1]: Started Custom key bindings for the side panel of razer mouses..
mar 02 09:55:28 garuda nagaServerCatcher.sh[7282]: Starting X11
mar 02 09:55:28 garuda nagaServerCatcher.sh[7292]: Stopping possible naga daemon
mar 02 09:55:28 garuda nagaServerCatcher.sh[7309]: Authorization required, but no authorization protocol specified
mar 02 09:55:28 garuda nagaServerCatcher.sh[7309]: Unable to connect to X server
mar 02 09:55:28 garuda nagaServerCatcher.sh[7317]: Authorization required, but no authorization protocol specified
mar 02 09:55:28 garuda nagaServerCatcher.sh[7317]: Unable to connect to X server
mar 02 09:55:28 garuda nagaServerCatcher.sh[7292]: Reading from: /dev/input/by-id/usb-Razer_Razer_Naga_Pro_000000000000-if02-event-kbd
mar 02 09:55:28 garuda nagaServerCatcher.sh[7292]: and /dev/input/by-id/usb-Razer_Razer_Naga_Pro_000000000000-event-mouse

If i remade the installation it starts to work.

The third problem is in kde XF86AudioRaiseVolume doesn't work, but Lower and Mute works. That's very stranghe, but i think is a kde problem.

Thanks again for your work and have a nice day.

**Comment by lostallmymoney** [comment]
Also it'd be nice to have a clean log from the building of nagaWayland.cpp ,
try running from inside the main folder  :
g++ -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/dbus-1.0 ./src/nagaWayland.cpp -o ./src/nagaWayland -pthread -Ofast --std=c++2b -ldbus-1
and post the logs here if you are willing ! Thanks

**Comment by lostallmymoney** [comment]
Also I'm starting to have issues with my side pannel button starting to die. I was having doubts and confusion before I realised trying to debug ahah. I'm wondering if your XF86AudioRaiseVolume macro isn't linked to a dead sidepanel button too ;)

**Comment by lostallmymoney** [comment]
P.S.
you can list the currently selected keycodes (to see if you have more than one XF86AudioRaiseVolume) using:

$ xmodmap -pk

If you have more than one keycode it's reported not to work, a KDE bug. Try disabling with something like 
$ xmodmap -e "keycode 175 ="

**Comment by lostallmymoney** [comment]
Also idk if it could be related but if you ever start a shell only session and start naga inside of it you won't be able to restart it before you shutdown inside the shell session. So if you got that zombie state that might something to look into. You might have to import the environment in X11 just like I do with wayland.

**Comment by Stibax** [comment]
> Tell me if "naga start" works. I got that error on wayland when it was trying to start before any user logged in. If it does work, try the command "who", count the number of rows, if you are above of 2 rows on a cleanly booted system maybe there's more sessions running so it would start too early. Go inside of NagaServerCatcher and set the -lt condition to the number of outputs from who : while [ "$(who | wc -l)" -lt 2 ]; do -> while [ "$(who | wc -l)" -lt 3 ]; do Tell me if it works. Thanks

Hi,
if i do naga start it won't start and naga debug give me the same error.
the who command print this on fresh start:

stibax   tty2         2024-03-02 17:06 (:0)
stibax   pts/0        2024-03-02 17:06 (:0)

So if i understand well, it's correct?

**Comment by Stibax** [comment]
> P.S. you can list the currently selected keycodes (to see if you have more than one XF86AudioRaiseVolume) using:
> 
> $ xmodmap -pk
> 
> If you have more than one keycode it's reported not to work, a KDE bug. Try disabling with something like $ xmodmap -e "keycode 175 ="
> 
> Post is from 2006 tho and is supposedly fixed.

No i don't have any duplicate keycode:

xmodmap -pk | grep Volume    tell me ;

122         0x1008ff11 (XF86AudioLowerVolume)       0x0000 (NoSymbol)       0x1008ff11 (XF86AudioLowerVolume)
123         0x1008ff13 (XF86AudioRaiseVolume)       0x0000 (NoSymbol)       0x1008ff13 (XF86AudioRaiseVolume)

**Comment by Stibax** [comment]
Now the volume uo button works, it was only a fault contact. I have notice that in manjaro the command who show me only this:

stibax   + tty2         2024-03-02 18:27 00:01       18618 (:0

**Comment by lostallmymoney** [comment]
Try installing libdir for the wayland installation.
You can try fiddling with xhost inside of nagaservercatcher to add more env variables to the session. You can also try to use the env file I created for the wayland session, but for X11. My guess is wrong display.

Try changing the display to :0 in nagaservercatcher

**Comment by lostallmymoney** [comment]
Try installing libdir for the wayland installation.
You can try fiddling with xhost inside of nagaservercatcher to add more env variables to the session (this might import the right dbus or display var). You can also try to use the env file I created for the wayland session, but for X11. My guess is wrong display.

Try changing the display to :0 in nagaservercatcher

Naga uses display to send events to,
It also uses dbus to gather info about current windows.

Try adding a 10 second sleep after the verification if a logged in user is finished to prevent it to launch too early.

**Comment by lostallmymoney** [comment]
If all the above does not succeed, create a script to start on startup on KDE.
Start by manually disabling the service :
sudo systemctl naga stop

Then remove the persistence line i added to .profile :
--sudo systemctl start naga
(This may be the reason this is not working btw).


And for startup run this command inside of the script :
nagaX11 serviceHelper

This should bypass everything and work straight away as long as the timing of the execution is right.

**Comment by lostallmymoney** [comment]
Hey good news I got it running in garuda kde with wayland. I will not focus on X11 because wayland is better anyways in term of fps with dual monitors.

The first fix is the compiling, you can fix by changing the g++ line to :

g++ -I/usr/lib64/dbus-1.0/include -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/dbus-1.0 ./src/nagaWayland.cpp -o ./src/nagaWayland -pthread -Ofast --std=c++2b -ldbus-1

The second fix is to fix dotool and the includes for garuda.

Start by installing go.
extra/go
Then install scdoc

Then install naga and it should work.

**Comment by Stibax** [comment]
Hi,
sorry for me wayland session is unstable. I have mouse trails, missing character in browser ecc ecc. I think it's bacause i have a nvidia card (rtx3080) i suppose you have and amd or intel! So for now i have to stay with x11.
in anyway i try the new g++ line and it work, it compile and start.
I have uninstall, delete the git repo. Redo the git clone and reinstall without wayland support and it finish the installation, but i notice this output during compile:

Compiling code...
./src/nagaX11.cpp: In static member function ‘static const void NagaDaemon::runAndWrite(const std::string*)’:
./src/nagaX11.cpp:369:51: warning: ignoring attributes on template argument ‘int (*)(FILE*)’ [-Wignored-attributes]
369 |                 unique_ptr<FILE, decltype(&pclose)> pipe(popen(macroContent->c_str(), "r"), pclose);
|                                                   ^
cp: not replacing '/home/stibax/.naga/keyMap.txt'


After installation it works as always but after reboot it doesn't work and naga debug give the error posted obove about:
Authorization required, but no authorization protocol specified.

Now i will try what you suggest, but some steps i cannot understand:

>"try changing the display to :0 in nagaservercatcher" 

in this file i have no line with display 

The other solution you explain about a starting script, i don't understand this:

>Then remove the persistence line i added to .profile :
--sudo systemctl start naga
(This may be the reason this is not working btw).

What you mean when you say ".profile" i have any file .profile.

Thanks again for you support.

**Comment by lostallmymoney** [comment]
Hi. Try copying the config files to /root/.naga first. Then try running nagaX11 serviceHelper .
You might also try installing the script as root.
________________________________

**Comment by lostallmymoney** [comment]
The .profile file is a file in ubuntu that is ran on user login. I add a line to start the service as backup.
________________________________

**Comment by lostallmymoney** [comment]
And what I mean is that it looks like qhen your system is booting up it's running the service appart from the visual session (x11) so it cannot get info to it/from it. The X11 session registers itself as a display, in this case :0. I believe you can call display=:0 in the catcher script (may be uppercase).

This may be due to errors with dbus also. You may try a version before the autoprofiles to see if it works. The simpler the version, potentially the better for you.

Also I do not get the nvidia errors you are getting. Latest driver 550. Wayland is also much smoother on my dual monitor setup because it allows my 144hz monitor to have 144hz desktop, while my 60hz has 60. X11 locks everything to 60 :/
________________________________

**Comment by lostallmymoney** [comment]
And once wayland version is working, you may run wayland on X11, it is compatible. But if you want better functionality from X11, I am a bit clueless now as I did not succeed at getting it running.
________________________________

**Comment by Stibax** [comment]
hi,
i have try to install the version 14,20 but the same errora accurs. I make some research about the error that lead me to the xauthority file. Because i haven't any knowledge of coding script, for what i understand the problem is that when start it doesn't know the corract display where x11 is? I've notice that in Garuda i have no xauthority file like i had in manjaro, but in the /tmp folder.  I've found this thread  https://www.reddit.com/r/archlinux/comments/15s33yk/xauthority_file_in_tmp_and_not_in_user_home/
but i haven't the knowledge to understand if it is related or not to my problem. 
Thanks

**Comment by lostallmymoney** [comment]
Some people reported installing xorg-host to fix similar issue.
You may verify that the group is still permanent (razerInputGroup).
You can also modify the setup to reinstall everytime you startup for now ahah !

**Comment by lostallmymoney** [comment]
Is this still an issue ? Since wayland can be run on X11, I suggest for anyone to modify nagaServerCatcher to 
`#!/bin/sh
#Finds the visual server and starts the right one
while [ "$(who | wc -l)" -lt 2 ]; do
	sleep 1
done
echo "Starting Wayland"
gnome-extensions enable window-calls-extended@hseliger.eu
killall dotoold >/dev/null 2>&1
setsid bash -c 'dotoold' &
if [ $# -eq 0 ]; then
nagaWayland serviceHelper
else
nagaWayland serviceHelper $1
fi
`

This should make it use dotool only and be compatible on X11 with less functionnality but witth most of the essential stuff.
If anything else is needed please contact me and I might be able to troubleshoot one day !
